#!/bin/bash
# Quick deployment guide for Demand-X

echo "🚀 Demand-X Deployment Setup"
echo "================================"
echo ""
echo "Step 1: Backend Deployment (Railway)"
echo "-------------------------------------"
echo "1. Go to https://railway.app"
echo "2. Click 'New Project' → 'Deploy from GitHub'"
echo "3. Select your Demand-X repository"
echo "4. Set environment variables:"
echo "   - FLASK_ENV=production"
echo "   - SECRET_KEY=your_secret_key"
echo "5. Click Deploy"
echo "6. Copy your Railway backend URL (e.g., https://demand-x-backend.railway.app)"
echo ""
echo ""
echo "Step 2: Frontend Deployment (Vercel)"
echo "-------------------------------------"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Click 'Add New' → 'Project'"
echo "3. Import your Demand-X repository"
echo "4. Set environment variable:"
echo "   - REACT_APP_API_URL=https://your-railway-backend-url"
echo "5. Click Deploy"
echo "6. Your frontend will be live at vercel URL"
echo ""
echo ""
echo "Step 3: Update CORS (if needed)"
echo "--------------------------------"
echo "Edit backend/app.py and update CORS to allow Vercel domain"
echo ""
echo "Deployment Complete! 🎉"
echo ""
echo "Your app will be accessible at:"
echo "  Frontend: https://your-app.vercel.app"
echo "  Backend: https://your-app.railway.app"
